// <auto-generated />
namespace StudentAttendanceSystemGW.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nint1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nint1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905011735181_nint1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
